services:
  app:
    build: .
    ports:
      - "8501:8501"
      - "8888:8888"
    volumes: 
      - ../:/app
    environment:
      - JUPYTER_TOKEN=grupo1
      - TF_CPP_MIN_LOG_LEVEL=2
    working_dir: /app
    # Enrique (no tiene gpu)
    # shm_size: '2gb' # Aumentamos memoria compartida para que el modelo cargue mejor

    deploy:
      resources:
        reservations:
          devices:
            driver: nvidia
            count: all
            capabilities: [gpu]